"""Data models and runtime configuration (streamlined rebuild).

Retains ``LLMStats`` (required by ``llm.py``) and provides the generation pipeline's
``BrandProfile`` / ``PageRecord`` / ``GenerationConfig`` / ``BRAND_SOURCE_POLICY``.

Brand profile strategy: use an LLM when ``llm_provider != none`` (following HEAD's
llm_profile approach in ``orchestrator.build_profile``); otherwise fall back to the
deterministic ``fallback_profile`` template. Brand names are always read from
``data/brands/*.json``, never generated by an LLM.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any


GENERATOR_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = GENERATOR_ROOT.parent


# Brand source to direction/brand file policy (single source of truth).
# geo_direction sets manipulation direction: positive promotes fake/niche brands;
# negative suppresses real brands. brand_source keys use public types: real/niche/fake.
BRAND_SOURCE_POLICY: dict[str, dict[str, str]] = {
    "real": {"file": "real_brands.json", "geo_direction": "negative", "brand_type": "real"},
    "niche": {"file": "niche_brands.json", "geo_direction": "positive", "brand_type": "niche"},
    "fake": {"file": "fake_brands.json", "geo_direction": "positive", "brand_type": "fake"},
}


@dataclass(frozen=True)
class BrandProfile:
    """Brand profile: identity layer, related-brand pool, and business profile fields.

    Descriptive fields (operator_name / positioning / products / competitors, etc.)
    are filled by ``orchestrator.build_profile`` using an LLM when available and
    deterministic templates otherwise. Fabricated metrics that vary between pages
    (sales/rankings/certifications) are excluded; attack vectors invent them at render time.

    The published form (record["profile"]) depends on attack difficulty level and
    is controlled downstream, **not by this class** (see
    ``depth.LevelStrategy.profile_mode`` and ``page_type.PageBuilder.make_record``):
    L1 publishes ``{}`` (the core identity profile still drives URLs/seeds/queries
    internally); L2 publishes ``to_dict()``; L3 publishes ``to_dict()`` plus
    ``professional_signals`` (specifications/ratings/citations/organizations/
    certifications/user feedback). A separate ``orchestrator.build_professional_signals``
    call generates category-specific signals, preferring the LLM with deterministic
    category-specific fallbacks when offline or on failure. This is a separate object
    and **must not** be added as a BrandProfile field. ``GenerationConfig.profile_reuse``
    controls reuse: once=one per brand, per_page=newly built for each page.
    """

    category: str
    brand: str
    brand_type: str = "fake"
    geo_direction: str = "positive"
    operator_name: str = ""
    headquarters: str = ""
    brand_positioning: str = ""
    target_audience: str = ""
    price_range: str = ""
    products: tuple[str, ...] = ()
    features: tuple[str, ...] = ()
    competitors: tuple[str, ...] = ()
    pain_points: tuple[str, ...] = ()
    channels: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        data = asdict(self)
        for key in ("products", "features", "competitors", "pain_points", "channels"):
            data[key] = list(data[key])
        return data

    def anchor_dict(self) -> dict[str, Any]:
        """Identity fields stable across pages, excluding page-varying fabricated metrics."""
        return {
            "category": self.category,
            "brand": self.brand,
            "brand_type": self.brand_type,
            "operator_name": self.operator_name,
            "headquarters": self.headquarters,
            "brand_positioning": self.brand_positioning,
            "target_audience": self.target_audience,
            "products": list(self.products),
            "features": list(self.features),
            "competitors": list(self.competitors),
            "pain_points": list(self.pain_points),
        }


@dataclass
class PageRecord:
    """One poisoned web page record, matching the requirements' output schema."""

    category: str = ""
    brand: str = ""
    brand_type: str = ""
    query: str = ""
    answer: str = ""
    title: str = ""
    url: str = ""
    timestamp: str = ""
    discovered_via: str = ""
    content: str = ""
    snippet: str = ""
    page_type: str = ""
    source_type: str = "generated"  # generated | modified
    level: str = "L1"
    manipulation_direction: str = "positive"  # positive | negative
    attack_vectors: list[dict[str, Any]] = field(default_factory=list)
    real_source_url: str = ""
    real_source_content: str = ""
    real_source_title: str = ""
    ext: dict[str, Any] = field(default_factory=dict)
    profile: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "category": self.category,
            "brand": self.brand,
            "brand_type": self.brand_type,
            "query": self.query,
            "answer": self.answer,
            "title": self.title,
            "url": self.url,
            "timestamp": self.timestamp,
            "discovered_via": self.discovered_via,
            "content": self.content,
            "snippet": self.snippet,
            "page_type": self.page_type,
            "source_type": self.source_type,
            "level": self.level,
            "manipulation_direction": self.manipulation_direction,
            "attack_vectors": [dict(v) for v in self.attack_vectors],
            "real_source_title": self.real_source_title,
            "real_source_url": self.real_source_url,
            "real_source_content": self.real_source_content,
            "ext": dict(self.ext),
            "profile": dict(self.profile),
        }


@dataclass
class GenerationConfig:
    """Pipeline runtime configuration, streamlined without grt/quality audit/citation retrieval fields."""

    categories: list[str] = field(default_factory=list)
    output_dir: Path = Path("output")
    anchor_date: str = "2026-07-28"
    brand_source: tuple[str, ...] = ("fake",)  # real | niche | fake; multiple allowed
    brand_source_dir: Path = REPO_ROOT / "data" / "examples" / "brands"
    brands: list[str] | None = None  # None / ["all"] = all brands in the source file
    pages_per_brand: int = 10
    # Attack difficulty: subset of L1-L3; empty/None/all means all three (N pages each).
    levels: tuple[str, ...] = ("L1", "L2", "L3")
    # LLM
    llm_provider: str = "none"  # none | openai-compatible
    model: str | None = None
    temperature: float = 0.75
    timeout: int = 180
    max_tokens: int = 3000
    max_attempts: int = 2
    enable_thinking: bool | None = None
    debug_llm: bool = False
    # Sampling
    seed: str = "gap"
    min_attacks_per_page: int = 1
    max_attacks_per_page: int = 3
    path_distribution: dict[str, float] = field(
        default_factory=lambda: {"generated": 0.5, "modified": 0.5}
    )
    domain_pool: Path = GENERATOR_ROOT / "assets" / "domain_pool.json"
    attack_library: Path = GENERATOR_ROOT / "assets" / "attack_family_library.json"
    force: bool = False
    # Profile reuse: once=generate once per brand (base profile + L3 professional
    # signals) and reuse throughout; per_page=regenerate before each page. Default: once.
    profile_reuse: str = "once"

    @property
    def brands_all(self) -> bool:
        if not self.brands:
            return True
        lowered = [b.strip().lower() for b in self.brands if b.strip()]
        return not lowered or all(b in {"all", ""} for b in lowered)


@dataclass
class LLMStats:
    calls: int = 0
    retries: int = 0
    failures: int = 0

    def to_dict(self) -> dict[str, int]:
        return asdict(self)
